Improvement/05 triathlon
TomasKostadinov/dhbw-svm-outdoor pull request #39
Opened 2019-11-06 03:31 UTC by BlueEnni

@TomasKostadinov please add the remaining html files to the combiner

triathlon/schwimmen/schwimmen.html
triathlon/schwimmen/trainingsplan-schwimmen.html
triathlon/laufen/laufen.html
triathlon/laufen/trainingsplan-laufen.html
triathlon/radfahren/radfahren.html
triathlon/radfahren/trainingsplan-radfahren.html
triathlon/mobi-stabi-training/mobi-stabi-training.html
triathlon/mobi-stabi-training/trainingsplan-mobi-stabi-training.html

2019-11-06 14:27 UTC, TomasKostadinov requested changes
More on this later, could not see it as it is currently not beeing deployed

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/index.html
> +                            <a href="index.html">Home</a>
Please don't use filenames. We later want to have clean urls like /triathlon (the server will find /triathlon/index.html).
Therefor also rename all files to index.html

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/index.html
> +                            <a href="laufen/laufen.html">Laufen</a>
Change to /triathlon/laufen

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/index.html
> +                            <a href="schwimmen/schwimmen.html">Schwimmen</a>
Change to /triathlon/schwimmen

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/index.html
> +                            <a href="radfahren/radfahren.html">Radfahren</a>
Also here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/laufen/laufen.html
> +                            <a href="../index.html">Home</a>
Change to /triathlon

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/laufen/laufen.html
> +                            <a href="laufen/laufen.html">Laufen</a>
Change this

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/laufen/laufen.html
> +                            <a href="schwimmen/schwimmen.html">Schwimmen</a>
Change this

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/laufen/laufen.html
> +                            <a href="radfahren/radfahren.html">Radfahren</a>
Change this

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/laufen/trainingsplan-laufen.html
> +                            <a href="../index.html">Home</a>
Also here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/mobi-stabi-training/mobi-stabi-training.html
> +                            <a href="../index.html">Home</a>
An here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/mobi-stabi-training/trainingsplan-mobi-stabi-training.html
> +                            <a href="../index.html">Home</a>
An here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/radfahren/radfahren.html
> +                            <a href="../index.html">Home</a>
And here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/radfahren/trainingsplan-radfahren.html
> +                            <a href="../index.html">Home</a>
And here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/schwimmen/schwimmen.html
> +                            <a href="../index.html">Home</a>
And here

2019-11-06 14:27 UTC, TomasKostadinov commented on site/triathlon/schwimmen/trainingsplan-schwimmen.html
> +                            <a href="../index.html">Home</a>
And here

2019-11-09 01:24 UTC, BlueEnni reviewed
Changed the destination path

2019-11-10 19:53 UTC, TomasKostadinov approved these changes
Seems fine ¯\_(ツ)_/¯

2019-11-10 19:53 UTC, merged